name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./download_deps.sh 
        shell: bash
      - run: ./release.sh 
        shell: bash
